### ISSUE TITLE
Sub Dynamics

### ISSUE THREAD

**Issue by oliverfriedmann** [betajs/betajs-dynamics#20]
Allow something like:

<ba-list>
  <item>
    <ba-item ba-itemmodel="{{itemmodel}}" ba-config="{{config}}">
    </ba-item>
  </item>
</ba-list>

**Comment by oliverfriedmann** [comment]
Something like what? Comments like this are not that helpful, Oliver.

**Comment by VictorLingenthal** [comment]
Is this from you originally?
Just looking at the issue tracker, I feel it got better from the last time I used it?

**Comment by oliverfriedmann** [comment]
Yeah, I wrote that (but no idea what I was trying to remind us of, so I closed it now...) - might be a little better now, yeah.
